# Generated by Django 4.1.5 on 2023-02-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Manufacture',
        ),
    ]
