# Generated by Django 4.1.5 on 2023-02-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_manufacturer_manufacture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacture',
            old_name='category_img',
            new_name='logo',
        ),
    ]
