# Generated by Django 4.1.5 on 2023-02-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_category_img_manufacture_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='manufacture',
        ),
    ]
