# Generated by Django 4.1.5 on 2023-02-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_manufacturer_product_manufacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(upload_to='campaign_images/')),
            ],
        ),
    ]
